
## REM: makes no sense, because no Get on root
GET /
#GET /gbx/data/
Host: {{host}}:{{port}}
##
Authorization: Basic {{Basic_user_jott}}
#ids-securityToken: {{IDS_DAT_connector_jott}}
##
Accept: application/ld+json
#Accept: text/turtle

###

GET /about
#GET /gbx/data/
Host: {{host}}:{{port}}
##
Authorization: Basic {{Basic_user_jott}}
#ids-securityToken: {{IDS_DAT_connector_jott}}
##
Accept: application/ld+json
#Accept: text/turtle

###

## request ConnectorDescriptionMessage
POST /
Host: {{host}}:{{port}}
Authorization: Basic {{Basic_user_jott}}
Content-Type: multipart/form-data; boundary=msgpart

--msgpart
Content-Type: application/json; charset=utf-8
Content-Disposition: form-data; name="header"

{
  "@context" : "https://w3id.org/idsa/contexts/context.jsonld",
  "@type" : "ids:DescriptionRequestMessage",
  "id" : "http://industrialdataspace.org/connectorAvailableMessage/34d761cf-5ca4-4a77-a7f4-b14d8f75636a",
  "issued" : "2019-12-02T08:25:08.245Z",
  "modelVersion" : "3.0.0",
  "issuerConnector" : "https://companyA.com/connector/59a68243-dd96-4c8d-88a9-0f0e03e13b1b",
  "securityToken" : {
    "@type" : "ids:DynamicAttributeToken",
    "tokenFormat" : "https://w3id.org/idsa/code/tokenformat/JWT",
    "tokenValue" : "eyJhbGciOiJSUzI1NiIsInR5cCI..."
  }
}

--msgpart
Content-Type: application/json
Content-Disposition: form-data; name="payload"

{
}

###

GET /.well-known/jwks.json
#GET /gbx/data/
Host: {{host}}:{{port}}
##
#Authorization: Basic {{Basic_user_jott}}
#ids-securityToken: {{IDS_DAT_connector_jott}}
##
#Accept: application/ld+json
#Accept: text/turtle

###

POST /token
Host: {{host}}:{{port}}
Authorization: Basic {{Basic_user_jott}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJkZW1vY29ubmVjdG9yMSIsInN1YiI6ImRlbW9jb25uZWN0b3IxIiwiZXhwIjoxNTQ4Nzg1Mzg2LCJuYmYiOjE1NDg3ODE3ODYsImlhdCI6MTU0ODc4MTc4NiwiYXVkIjoiaHR0cHM6Ly9hcGkubG9jYWxob3N0In0.JSQuMf-9Fd7DNna_-s-sR7eXgcSYNCau5WgurrGJTuCSLKqhZe3odXfunN2vRFgUhU21ADFlEq96mlbQDueBlMtaXrcHFPSpIUtvuIMIVqQcGYkDdSJr_VmDuAykCYpyTCkLa7a8DTV-N3sECp-AxUgmEzYIfh8jW0WS6ehgUzrnpH6t_h_GWXKkNSAg3ERakDc4NY02pBGmiN7bmtLZNt5b4LWALiiFiduC7JbIpx4awOU6skMApmzgLnZmmTG20JlJRg6hAqyHEz5Cd4rUgrt0twmpC0Us_CG23KdUF5fWI55dcO2qAVvhNQXpqz7IiPcF7-jgkrx4oukYNY6eHA&scope=ids_connector_attributes

###

